apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
      #definir qualquer valor entre 30000 ate 32767
      nodePort: 30000
  selector:
    app: primeiro-pod